### PR TITLE
Tweak Video and Photo Conversion

### PR DESCRIPTION
**Pull request by noczero**
# Context
I had a bad quality video conversion when recording 4k (2160 x 3840) portrait videos. 
After running the import command, it converts to 406×720 which is not 720p or HD, and gets the wrong aspect ratio. 
It also set the frame rate to 30 fps which gives a flickering frame rate.

# Solution
I have updated some code to give me a better video quality after conversion with a respected lower file size.
So in this case, if we have 4k video it will reduce to 2k, and 1080p will reduce to 720p. 
It rescales both width and height to half of the size and also keeps the original fps for smooth motion.

# Additional
I have tweak also the image to support 2k conversion, keep the original quality, and increase the image default small and large size.

### CODE REVIEW

**Comment by xemle** [comment]
Hi @noczero 

awesome for this great PR. Thank you very much.

Would you mind to have a call about this because it breaks some of the design such as mobile friendlyness regarding data consumption. On other issues your changes are requested, too. So I would like to discuss possible solutions for it before merging it.

My time zone is Europe/Berlin. 21h local time would be awesome for me.

**Comment by xemle** [comment]
Hi @noczero 

regarding to your awesome PR I would like to discuss following things. First of all I like the format and description you are posting the request. The PR covers two things: Change of video conversion and increase the preview image. Both covers a improve or customization of settings. I would like to split both topics to separate PRs and talk first about customization

## Customization

The gallery could have better support for extractor customization such as preview size (#62), video transcoding (#74). enable/disable extractors like the api (#37) and your PR. Due project's history there were first the CLI calls with different arguments and later the configuration file `gallery.config.yml` was introduced (5264286) while the arguments where build from the config.

In v1.10.0 the server command uses mainly the `gallery.config.yml` instead of the arguments (e8e47de). I would like to see these switch from cli args to `gallery.config.yml` also for the extractor to have better customization support. Than your demand of customization of video previews and different preview image can be only a setting.

How do you like this idea?

## Video conversion

The current video conversion setting targets main mobile phones. 720p was chosen to have a good balance between common FullHD desktop resolution, mobile devices, bandwidth consumption, load time and disk consumption. Therefore the baseline is 3.0 and not 4.0. The decision is 3 years old and maybe it can be upgraded to be baseline 4.0.

#74 requests already some customization of the encoder. So I would not mind to move your improvement to the similar direction.

## Portrait videos

I do not have many portrait videos and even less 4K portrait videos. If the video is not scaled properly that would be a bug which should be fixed. How is the final resolution of your 2160 x 3840 portrait videos in the original code?

## Image preview

As stated before I would be happy if this request can be customized in the `gallery.config.yml`. Some code parts needs to be updated to handle more than 1920 previews.

Is there a reason why you changed the [EntryMarker.tsx](https://github.com/noczero/home-gallery-custom/commit/ec82fc7ba8e657e6b225517d8265a337f6072581#diff-3b685106ed90558648563b54354a30593c275d83ce92e6be8ccbf062bc0e162e) and [MediaNav.tsx](https://github.com/noczero/home-gallery-custom/commit/ec82fc7ba8e657e6b225517d8265a337f6072581#diff-06dfa84f16ee1c0b40be1e26f4c19aa02d2c87c8bf4b0914a93113086fee9400) regarding the preview sizes? Do you try to cover a retina display? What is your thought about mobile devices and bandwidth consumption/loading time?

Ah, and also the image quality can be a custom setting, too.

## Outlook

One great idea would be to support also a kind of plugin architecture where the advance user can hook into the workflow of the gallery to extend the extractor, the database entry, the search and even the web app by supporting webp file format, geo tracks, motion pictures, video subtitle generation, other ML based data extraction etc, etc.

By being enthusiastic on the gallery topic I have to be realistic as well: This project is currently a one-man-show and a pet project. So it needs either a better community with dev support or patience from the customers until all the great features are implemented.

**Comment by noczero** [comment]
Hi @xemle, thanks for being patient. I'm not really available on weekdays. I've use this PR for a while and this is the best settings for me.

Based on what you approach, let me clarify few things and maybe I can help you with this.
1. I agree about storing the video conversion, image conversion, and image preview customization in `gallery.config.yml` as environment variable. 
I'm thinking to named set it in new field called conversion settings for conversion things and preview field for image and video preview.
``` js
conversion:
  # Video and image conversion settings.
  video:
    # Set value in range to 0-100% for video dimension reducer. 
    conversionRate: 50

    # Set the minimal resolution after conversion. this enum to more familiar likes value HD -> (720p), FHD -> (1080p), QHD -> (2k), UHD -> (4k).
    videoResolutionLimit: FHD,

    # More advance options ffmpeg encoder. 
    outputOptions: ['-y' , '-preset slow', '-tune film', ....]

  image:
    # Set value in range to 0-100% for image quality,
    quality: 100
   
preview:
  # Video and image preview settings.
  video:
    # i dont see possible preview setting on this yet.
    
  image:
    # list of image resizer resolution.
    imagePreviewSizes: [2048, 1920, 1280, 800, 320, 128]
    
    # Set value as image thumbnail resoulutio, it must match with item in imagePreviewSizes list. 
    lowResolutionImage: 800,
    
    # Set value as main image view, it must match with item in imagePreviewSizes list.
    highResoultionImage: 2048,
    
    # Set to true will fallback to second highest imagePreviewSizes based on Screen size of body screen dimension.
    # set to false to keep use high resoultion image. 
    dynamicResolution: true, 
    
``` 

2. Yeah about the potrait videos, there's a bug when convert a video with 2160 x 3840 dimension, it results 406 × 720 dimension, not 720 x 1080. 
It's caused by `scale=-2:'min(720,ih)'`.

3. I know you have a many ideas to come with and I really appreciate your hard work in this project. 
If I may give a idea to this project, For better story of our image and support for disabilities, I think we need to make image descriptions, also called alternative text (ALT) similar in Twitter. Sounds good right?

**Comment by xemle** [comment]
Hi @noczero 

I used your PR to implement custom image and video previews via the `gallery.config.yml`. See [configuration docs](https://docs.home-gallery.org/configuration/index.html#full-configuration):

```
#extractor:
  # Preview image settings
  #image:
  #  previewSizes: [1920, 1280, 800, 320, 128]
  #  previewQuality: 80
  #video:
  #  previewSize: 720 # used as preview size and preview filename
  #  ext: mp4 # used as target video container and preview filename
  #  scale: -2:'min(720,ih)' # overwrites previewSize. E.g. -2:'min(ih,max(720,min(1080,ih*.5)))' for 720p <= height*0.5 <= 1080p or height, if height < 720
  #  frameRate: 30
  #  maxVideoBitRate: 4000 # in KB
  #  videoEncoder: libx264
  #  preset: slow
  #  profile: baseline
  #  level: '3.0'
  #  addFfmpegArgs: [...] # Additional ffmpeg args
  #  customFfmpegArgs: [...] # custom ffmpeg args for video conversion, replaces all other settings such previewSize, videoEncoder, addFfmpegArgs, ...
```

I hope it is OKish that your PR is not accepted directly in code. Your input and direction leads to the new v1.11.0 version with customizing image and videos. The size of portrait videos is fixed, too. Thank you very much for your valuable input and time.

See further changes on v1.11.0 in the [Changelog](https://docs.home-gallery.org/changelog.html)

**Comment by xemle** [comment]
By the way I encode my wrong portrait videos again. 

```
# Update the docker service
docker compose pull
docker compose up -d
# Fetch all portrait video previews and remove them in the storage directory using curl, jq, grep, sed
curl -s 'http://localhost:3000/api/database.json?q=video%20ratio<1' | jq .data[].previews | grep mp4 | sed 's/"//g' | while read f; do echo "Remove preview portrait video $f"; rm data/storage/$f; done
# Recreate the videos by a full import
docker compose run gallery run import
```

**Pull request closed without merging**
